### ISSUE TITLE
Error when podcast in playlist - Argument null exception on Swan.PropertyPropertyExtensions.ReadProperty

### ISSUE THREAD

**Issue by domportera** [fiso64/slsk-batchdl#14]
Thanks for making this! It's super handy. I'm running into a consistent issue after using it a few times, on smaller playlists successfully

**EDIT: I think I found the culprit - if a podcast is in the playlist, this error occurs**

```bash
❯ .\slsk-batchdl {{music playlist of any size with one or more podcasts in it}}
Windows: Recommended to use the command prompt instead of terminal app to avoid printing issues.
Loading Spotify tracks
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'obj')
   at Swan.PropertyProxyExtensions.ReadProperty[T](T obj, String propertyName)
   at Spotify.GetPlaylist(String url, Int32 max, Int32 offset)
   at Program.Main(String[] args)
   at Program.<Main>(String[] args)
```

Config:
```
--music-dir "D:/Sync/Music"
--path "D:/Sync/Music"
--folder "slsk-batchdl"
--username "myusernamelol"
--password "mypasswordlol
--spotify-id "myspotifyidlol"
--spotify-secret "topsecwet"
--display "single"
--min-bitrate 320
--max-bitrate 700
--pref-max-samplerate 48000
--skip-existing
```

**Comment by fiso64** [comment]
fixed
