### ISSUE TITLE
Search query must contain at least one non-exclusion term with length greater than 1 (Parameter 'query')

### ISSUE THREAD

**Issue by Avotien** [fiso64/slsk-batchdl#15]
Seems like that if a song name on a CSV is a single character long, this error pops up, and so skips the song.
```
Search query must contain at least one non-exclusion term with length greater than 1 (Parameter 'query')
   at Soulseek.SoulseekClient.SearchAsync(SearchQuery query, Action`1 responseHandler, SearchScope scope, Nullable`1 token, SearchOptions options, Nullable`1 cancellationToken)
   at Program.RunSearches(String search, SearchOptions opts, Action`1 rHandler, CancellationToken ct, Action onSearch)
   at Program.SearchAndDownload(Track track)
   at Program.<>c__DisplayClass82_0.<<Main>b__1>d.MoveNext()
```
slsk-batchdl.conf:
```
--random-login
--time-format m:s
--length-tol 99999
--no-artist-search
```
cmd:
`slsk-batchdl example.csv`

[example.csv](https://github.com/fiso64/slsk-batchdl/files/13733449/example.csv)

**Comment by fiso64** [comment]
fixed. I updated the latest release
