### ISSUE TITLE
The releaseCount argument must be greater than zero. (Parameter 'releaseCount') Actual value was 0.

### ISSUE THREAD

**Issue by livinin82** [fiso64/slsk-batchdl#40]
Not sure if this is related to my config or not. I get this at a certain point on 100s of songs after entering spotify-likes as an arg. Other playlists seem to be fine. I made the list into another [Playlist](https://open.spotify.com/playlist/1VRvdKDvYtqeu0Jstl3gtf?si=b2a8652529d54b9b) and got the same error. Here's my config:

`name-format="\{sartist}\{salbum}\{artist} - {title} [{year}]"
username="XXXX"
password="XXXX"
pref-format="flac"
fast-search="false"
skip-existing="true"
path="X:\XXXX\Music\Music\Playlists"
spotify-id="XXXX"
spotify-secret="XXXXX"
remove-from-playlist="false"
youtube-key="XXXX"
format="flac,wav,m4a,mp3"
album-art="largest"
concurrent-downloads="3"
desperate="true"
no-remove-special-chars="true"
remove-ft="true"
remove-brackets="true"
yt-dlp="true"`

Here's the full debug error:

```
Wait for login, state: Connected, LoggedIn
Search and download Parov Stelar - Chambermaid Swing (353s)

Exception thrown: System.ArgumentOutOfRangeException: The releaseCount argument must be greater than zero. (Parameter 'releaseCount')
Actual value was 0.
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at RateLimitedSemaphore.TryResetSemaphore()
   at RateLimitedSemaphore.WaitAsync()
   at Program.Search(String search, SearchOptions opts, Action`1 rHandler, CancellationToken ct, Action onSearch)
   at Program.RunSearches(Track track, ConcurrentDictionary`2 results, Func`4 getSearchOptions, Action`1 responseHandler, CancellationToken ct, Action onSearch)
   at Program.SearchAndDownload(Track track)
   at Program.<>c__DisplayClass113_0.<<TracksDownloadNormal>b__0>d.MoveNext()

The releaseCount argument must be greater than zero. (Parameter 'releaseCount')
Actual value was 0.
   at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
   at RateLimitedSemaphore.TryResetSemaphore()
   at RateLimitedSemaphore.WaitAsync()
   at Program.Search(String search, SearchOptions opts, Action`1 rHandler, CancellationToken ct, Action onSearch)
   at Program.RunSearches(Track track, ConcurrentDictionary`2 results, Func`4 getSearchOptions, Action`1 responseHandler, CancellationToken ct, Action onSearch)
   at Program.SearchAndDownload(Track track)
   at Program.<>c__DisplayClass113_0.<<TracksDownloadNormal>b__0>d.MoveNext()

```

**Comment by fiso64** [comment]
Fixed here: https://github.com/fiso64/slsk-batchdl/releases/tag/v2.2.5
