### ISSUE TITLE
Spotify Login crashing the app

### ISSUE THREAD

**Issue by RyzenInu** [fiso64/slsk-batchdl#43]
After trying to download my private playlist, and trying to login, it just crashes. Here are the logs:

```
PS C:\Users\RyzenInu\Desktop\Apps\Soulseek Batch Download> ./sldl "https://open.spotify.com/playlist/2S11ETQk1qwywDVw2Ht5xS?si=b18b21efb3cb47de&pt=069ead3e6be3f1b1ac0effcd54be5cb2"
Windows: Recommended to use the default command prompt to avoid printing issues.
Loading Spotify playlist
Spotify playlist not found. It may be set to private. Login? [Y/n]
y
Loading Spotify tracks
Unhandled exception. SpotifyAPI.Web.APIException: Resource not found
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request, CancellationToken cancel)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request, CancellationToken cancel)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers, CancellationToken cancel)
   at Spotify.GetPlaylist(String url, Int32 max, Int32 offset)
   at Program.SpotifyInput()
   at Program.Main(String[] args)
   at Program.<Main>(String[] args)
PS C:\Users\RyzenInu\Desktop\Apps\Soulseek Batch Download>
```

**Comment by fiso64** [comment]
Not sure why this is happening, it works fine for me. Doesn't require a login because it's not set to private. Have you tried it multiple times? Do other playlists work, e.g `sldl "https://open.spotify.com/playlist/37i9dQZF1DZ06evO0BB4jK" --print tracks`? If not please try `sldl "https://www.youtube.com/playlist?list=PLI_eFW8NAFzYAXZ5DrU6E6mQ_XfhaLBUX" -n 1 --print tracks`, does it work? If that still doesn't work then it likely doesn't have internet access for some reason.

For now, you can use one of the many spotify to csv tools and then download from the csv file as a workaround.

**Comment by RyzenInu** [comment]
I set the playlist public after creating the issue so I could use it, but it is supposed to be private. When I set the playlist to private, it causes the crash.

**Comment by fiso64** [comment]
Ok, this should be fixed in the latest release: https://github.com/fiso64/slsk-batchdl/releases/tag/v2.2.6
