### ISSUE TITLE
Unhandled exception. SmallestCSV.SmallestCSVParser+Error: Unrecognized character 'С' after a parsed column

### ISSUE THREAD

**Issue by venn2x** [fiso64/slsk-batchdl#47]
I'm getting this error when trying to download anything

Unhandled exception. SmallestCSV.SmallestCSVParser+Error: Unrecognized character 'С' after a parsed column
   at SmallestCSV.SmallestCSVParser.TryFinishLine()
   at SmallestCSV.SmallestCSVParser.ReadNextColumn(Boolean removeEnclosingQuotes)
   at SmallestCSV.SmallestCSVParser.ReadNextRow(Boolean removeEnclosingQuotes)
   at Program.ParseCsvIntoTrackInfo(String path, String artistCol, String trackCol, String lengthCol, String albumCol, String descCol, String ytIdCol, String trackCountCol, String timeUnit, Boolean ytParse)
   at Program.CsvInput()
   at Program.Main(String[] args)
   at Program.<Main>(String[] args)

**Comment by fiso64** [comment]
Post the csv
