### ISSUE TITLE
yt-dlp downloads : "Second path fragment must not be a drive or UNC name" errors

### ISSUE THREAD

**Issue by omasseau** [fiso64/slsk-batchdl#68]
Hello,

When I enable yt-dlp downloads I get these errors : 
`Second path fragment must not be a drive or UNC name. (Parameter 'expression')`

Exemples:

```
cd C:\dev\temp\music

sldl --username xxx --password xxx --pref-format "flac" --concurrent-downloads 10 --debug --no-progress --yt-dlp https://open.spotify.com/playlist/4F2epFwSgUSMG4KuF2RXfx?si=96a6100757fb460a
Using extractor: Spotify
Loading Spotify playlist
Got tracks

Downloading 28 tracks (246 already exist).
  Death on the Balcony - Years Gone By - Nhar Remix - Mixed (330s)
  Raavel - Wakalaka - Mixed (227s)
  IAM - Du rêve dans les veines - Live Studio (199s)
  Tiga - Ascending Into The Clouds (feat. Elisabeth Troy) - Original Mix (374s)
  Fatima Yamaha - Inspectiespiegel (206s)
  Lueenas - In the Search - trentemøller rework (288s)
  Hoenix - Goddess Of Liberty (342s)
  Hoenix - Lion Force (256s)
  DATAINTRÅNG - Chemotherapy (256s)
  DATAINTRÅNG - Labyrinth Domain (307s)
  ... (etc)
Login xxx
Connecting xxx
Setting share count
Logged in xxx
Update started
Wait for login, state: Connected, LoggedIn
Searching: Death on the Balcony - Years Gone By - Nhar Remix - Mixed (330s)
yt-dlp search: Death on the Balcony - Years Gone By - Nhar Remix - Mixed (330s)
yt-dlp download: Death on the Balcony - Years Gone By - Nhar Remix - Mixed (330s)
Second path fragment must not be a drive or UNC name. (Parameter 'expression')
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, CancellationTokenSource cts)
   at Program.DownloadTask(TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
Wait for login, state: Connected, LoggedIn
Searching: Raavel - Wakalaka - Mixed (227s)
yt-dlp search: Raavel - Wakalaka - Mixed (227s)
yt-dlp download: Raavel - Wakalaka - Mixed (227s)
Second path fragment must not be a drive or UNC name. (Parameter 'expression')
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, CancellationTokenSource cts)
   at Program.DownloadTask(TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
Wait for login, state: Connected, LoggedIn
Searching: IAM - Du rêve dans les veines - Live Studio (199s)
Searching: IAM - Du rêve dans les veines - Live Studio (199s)
yt-dlp search: IAM - Du rêve dans les veines - Live Studio (199s)
yt-dlp download: IAM - Du rêve dans les veines - Live Studio (199s)
Second path fragment must not be a drive or UNC name. (Parameter 'expression')
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, CancellationTokenSource cts)
   at Program.DownloadTask(TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
Wait for login, state: Connected, LoggedIn
Searching: Tiga - Ascending Into The Clouds (feat. Elisabeth Troy) - Original Mix (374s)
yt-dlp search: Tiga - Ascending Into The Clouds (feat. Elisabeth Troy) - Original Mix (374s)
yt-dlp download: Tiga - Ascending Into The Clouds (feat. Elisabeth Troy) - Original Mix (374s)
Second path fragment must not be a drive or UNC name. (Parameter 'expression')
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, CancellationTokenSource cts)
   at Program.DownloadTask(TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
Wait for login, state: Connected, LoggedIn
Searching: Fatima Yamaha - Inspectiespiegel (206s)
yt-dlp search: Fatima Yamaha - Inspectiespiegel (206s)
yt-dlp download: Fatima Yamaha - Inspectiespiegel (206s)
Second path fragment must not be a drive or UNC name. (Parameter 'expression')
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, CancellationTokenSource cts)
   at Program.DownloadTask(TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
```

**Comment by fiso64** [comment]
Please try it with [sldl_win-x86_self-contained.zip](https://github.com/user-attachments/files/18142241/sldl_win-x86_self-contained.zip)

It does not fix the issue, but it should output more information.

**Comment by omasseau** [comment]
Hello, here is the output:

```
Downloading 409 tracks (7654 already exist).
  Armand Van Helden - Work Me Gaddamit 1 (381s)
  Sonovac - Diamond Cut Diamond (121s)
  Jean Jacques Smoothie featuring Tara Busch - 2People [2009 Rework] [Simpleton Extended Mix] (309s)
  Gramatik - Rock The Most (461s)
  Tommi Bass - Tudor Rose (439s)
  Tommi Bass - Tudor Rose Luizo Ortega Remix - Luizo Ortega Remix (425s)
  ZZT - The Worm - Original Munch Version (267s)
  Gabriel Prokofiev - String Quartet No. 2: IV. — (Hot Chip Remix) (258s)
  Ken Hayakawa - Ocean (428s)
  Solemn Camel Crew - Childs Play (219s)
  ... (etc)
Login xxx
Connecting xxx
Setting share count
Logged in djmaol
Update started
Wait for login, state: Connected, LoggedIn
Second path fragment must not be a drive or UNC name. (Parameter 'expression')                                                                                                                                                      (0  %)   yt-dlp "ytsearch3:Armand Van Helden - Work Me Gaddamit 1" --print "%(duration>%s)s === %(id)s === %(title)s"
yt-dlp "86grZ5ur5Ck" -f bestaudio/best -ci -o "C:/music/Backup/Armand van Helden - Work Me! (Gadamit), Henry Street Music 1995.%(ext)s" -x
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, Config config, CancellationTokenSource cts)
   at Program.DownloadTask(Config config, TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
Wait for login, state: Connected, LoggedIn
All downloads failed: Sonovac - Diamond Cut Diamond (121s)                                                                                                                                                                          (0  %)   yt-dlp "ytsearch3:Sonovac - Diamond Cut Diamond" --print "%(duration>%s)s === %(id)s === %(title)s"
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, Config config, CancellationTokenSource cts)
   at Program.DownloadTask(Config config, TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
Wait for login, state: Connected, LoggedIn
Succeded: yt-dlp completed download for Jean Jacques Smoothie featuring Tara Busch - 2People [2009 Rework] [Simpleton Extended Mix] (309s)                                                                                          (100%)   yt-dlp "ytsearch3:Jean Jacques Smoothie featuring Tara Busch - 2People [2009 Rework] [Simpleton Extended Mix]" --print "%(duration>%s)s === %(id)s === %(title)s"
yt-dlp "KL-Yd9qrFLY" -f bestaudio/best -ci -o "C:/music/Backup/Jean Jacques Smoothie - 2 People (2001).%(ext)s" -x
Wait for login, state: Connected, LoggedIn
Second path fragment must not be a drive or UNC name. (Parameter 'expression')                                                                                                                                                      (0  %)   yt-dlp "ytsearch3:Gramatik - Rock The Most" --print "%(duration>%s)s === %(id)s === %(title)s"
yt-dlp "h7R3BSBOiI4" -f bestaudio/best -ci -o "C:/music/Backup/Gramatik - Rock the Most (StarSteady Remix).%(ext)s" -x
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, Config config, CancellationTokenSource cts)
   at Program.DownloadTask(Config config, TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
Wait for login, state: Connected, LoggedIn
Second path fragment must not be a drive or UNC name. (Parameter 'expression')                                                                                                                                                      (0  %)   yt-dlp "ytsearch3:Tommi Bass - Tudor Rose" --print "%(duration>%s)s === %(id)s === %(title)s"
yt-dlp "9X3-xZz0QMk" -f bestaudio/best -ci -o "C:/music/Backup/Tommi Bass & Mykill Softt - Tudor Rose.%(ext)s" -x
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, Config config, CancellationTokenSource cts)
   at Program.DownloadTask(Config config, TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
Wait for login, state: Connected, LoggedIn
All downloads failed: Tommi Bass - Tudor Rose Luizo Ortega Remix - Luizo Ortega Remix (425s)                                                                                                                                        (0  %)   yt-dlp "ytsearch3:Tommi Bass - Tudor Rose Luizo Ortega Remix - Luizo Ortega Remix" --print "%(duration>%s)s === %(id)s === %(title)s"
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, Config config, CancellationTokenSource cts)
   at Program.DownloadTask(Config config, TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
Wait for login, state: Connected, LoggedIn
Second path fragment must not be a drive or UNC name. (Parameter 'expression')                                                                                                                                                      (0  %)   yt-dlp "ytsearch3:ZZT - The Worm - Original Munch Version" --print "%(duration>%s)s === %(id)s === %(title)s"
yt-dlp "UKEDSYo_HMg" -f bestaudio/best -ci -o "C:/music/Backup/ZZT - The Worm (Original Munich Version).%(ext)s" -x
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, Config config, CancellationTokenSource cts)
   at Program.DownloadTask(Config config, TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
Wait for login, state: Connected, LoggedIn
Second path fragment must not be a drive or UNC name. (Parameter 'expression')                                                                                                                                                      (0  %)   yt-dlp "ytsearch3:Gabriel Prokofiev - String Quartet No. 2: IV. — (Hot Chip Remix)" --print "%(duration>%s)s === %(id)s === %(title)s"
yt-dlp "-VzZbdZjzrw" -f bestaudio/best -ci -o "C:/music/Backup/The Elysian Quartet & Gabriel Prokofiev - Quartet No.%(ext)s" -x
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, Config config, CancellationTokenSource cts)
   at Program.DownloadTask(Config config, TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
Wait for login, state: Connected, LoggedIn
Second path fragment must not be a drive or UNC name. (Parameter 'expression')                                                                                                                                                      (0  %)   yt-dlp "ytsearch3:Ken Hayakawa - Ocean" --print "%(duration>%s)s === %(id)s === %(title)s"
yt-dlp "MF82XXgH2hQ" -f bestaudio/best -ci -o "C:/music/Backup/Ken Hayakawa - Ocean.%(ext)s" -x
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, Config config, CancellationTokenSource cts)
   at Program.DownloadTask(Config config, TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
```

**Comment by omasseau** [comment]
PS: I notice the file is correctly downloaded on disk. But the file state is not updated in the sldl index file. So sldl tries to redownload the file each time.

Example:

For this log:
```
Second path fragment must not be a drive or UNC name. (Parameter 'expression')
yt-dlp "ytsearch3:Ken Hayakawa - Ocean" --print "%(duration>%s)s === %(id)s === %(title)s"
yt-dlp "MF82XXgH2hQ" -f bestaudio/best -ci -o "C:/music/Backup/Ken Hayakawa - Ocean.%(ext)s" -x
Error: SearchAndDownloadException
   at Search.SearchAndDownload(Track track, FileManager organizer, Config config, CancellationTokenSource cts)
   at Program.DownloadTask(Config config, TrackListEntry tle, Track track, SemaphoreSlim semaphore, FileManager organizer, CancellationTokenSource cts, Boolean cancelOnFail, Boolean removeFromSource, Boolean organize)
```

In _-index.sldl I have : 
`,Ken Hayakawa,Japanese Rose,Ocean,428,0,2,3`

Yet the given file is correctly on disk after the download:
`Ken Hayakawa - Ocean.m4a`

**Comment by fiso64** [comment]
Sorry, I still can't reproduce. Please try this build: 
[sldl_win-x86_self-contained.zip](https://github.com/user-attachments/files/18157302/sldl_win-x86_self-contained.zip)
Note the pdb file, which should be in the same directory as the executable. Try this exact command:
`sldl https://open.spotify.com/playlist/4F2epFwSgUSMG4KuF2RXfx?si=96a6100757fb460a --no-config --user 9d1j90as --pass ajsd012i --cd 1 --debug --no-progress -n 1 --yt-dlp`

**Comment by jwapico** [comment]
I'm getting the same errors but only when using the --yt-dlp-argument flag. Using just --yt-dlp works fine, but downloads a nameless opus file. I tried using the default argument string, '"{id}" -f bestaudio/best -cix -o "{savepath}.%(ext)s"', as mentioned in the docs, but then I get the error again.

**Comment by loganank** [comment]
I am running slsk-batchdl on a debian Linux server with these settings and was getting the same error until today. I tried replicating the error, and then saw a comment somewhere about ffmeg. It turns out I was using --yt-dlp but ffmpeg wasn't installed. as soon as I installed ffmpeg and ran the slsk-dl command again, all the songs downloaded successfully, and that path error went away.

**Comment by patrick-theprogrammer** [comment]
I wonder if this has something to do with situations where there are things like double quotes in `{savepath}`?

For me the few times this happens is when the YouTube video name has double quotes, so the yt-dlp command shown in debug logs has something like `-o “/path/song “special””`

Maybe some place in the tool needs to escape strings to be path safe? I use the regex option to remove double quotes but that doesn’t seem to apply to the out path of yt-dlp.

I’m running docker on Linux if that helps.

**Comment by rodrigojmr** [comment]
> For me the few times this happens is when the YouTube video name has double quotes, so the yt-dlp command shown in debug logs has something like `-o “/path/song “special””`
> 
> Maybe some place in the tool needs to escape strings to be path safe? I use the regex option to remove double quotes but that doesn’t seem to apply to the out path of yt-dlp.

Yeah, I still experience this.

```
SongJob: running fallback: Chamber Concerto in D Major, RV 95, La pastorella (arr. for recorder and orchestra): II. Largo (230986s)
SongJob: yt-dlp "ytsearch3:Chamber Concerto in D Major, RV 95, La pastorella (arr. for recorder and orchestra): II. Largo" --dump-json
SongJob: yt-dlp "exY2M_csDm4" -f bestaudio/best -ci -o "/folder/Chamber Concerto in D Major, RV 95, "La pastorella" (arr. for recorder and orchestra): II. Largo.%(ext)s" -x
SongJob: ERROR: Fixed output name but more than one file to download: /folder/Chamber Concerto in D Major, RV 95, La
SongJob: failed [All downloads failed]: Chamber Concerto in D Major, RV 95, La pastorella (arr. for recorder and orchestra): II. Largo
  Error: yt-dlp download failed with exit code 1: ERROR: Fixed output name but more than one file to download: /folder/Chamber Concerto in D Major, RV 95, La
```
